server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: citas
              uri: lb://gestion-de-citas
              predicates:
                - Path=/api/v1/citas

            - id: pacientes
              uri: lb://gestion-de-pacientes
              predicates:
                - Path=/api/v1/pacientes

            - id: pagos
              uri: lb://pagos
              predicates:
                - Path=/api/v1/pagos


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}