spring.application.name=Gestion-de-Pacientes
server.port=9002


# Database Connection URL (change 'your_db_name' to your actual database name)
spring.datasource.url=jdbc:mysql://localhost:3306/pacientes

# Database Credentials
spring.datasource.username=root
spring.datasource.password=

# MySQL Driver (Spring Boot 3+ uses com.mysql.cj.jdbc.Driver)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
